version: '3.7'

services:
  psql:
    container_name: psql
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonar_user
    networks:
      - jenqubenet

networks:
  jenqubenet:
