version: '3.7'

services:
  jenkins:
    container_name: JKS
    privileged: true
    build: .
    volumes:
      - jenkins-home:/var/jenkins_home
    ports:
      - 8080:8080
      - 5001:5000
    networks:
      - jenqubenet
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2GB
    restart: unless-stopped

  sonarqube:
    container_name: SQB
    image: sonarqube:lts
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar-data:/opt/sonarqube/data
      - sonar-log:/opt/sonarqube/logs
      - sonar-extensions:/opt/sonarqube/extensions
      - sonar_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://psql/sonarqube
      SONARQUBE_JDBC_USERNAME: sonar_user
      SONARQUBE_JDBC_PASSWORD: password123
    ports:
      - 9000:9000
    networks:
      - jenqubenet

  psql:
    container_name: psql
    image: postgres:14.5-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonar_user
    networks:
      - jenqubenet

volumes:
  jenkins-home:
  sonar_conf:
  sonar-data:
  sonar-log:
  sonar-extensions:
  sonar_bundled-plugins:

networks:
  jenqubenet:
